### PR TITLE
SVD files from Symgrate's IDE collection project (see http://symgrate…

### PR DESCRIPTION
**Pull request by evm-sec**
….com)

### CODE REVIEW

**Comment by evm-sec** [comment]
For the Symgrate project we pulled down a plethora of old IDE versions to fingerprint standard libraries.  We really like your repo and want to contribute our pile of SVDs in a neighborly way.  So recently we pulled out all of the SVD files and compared them against cmsis-svd.  The bulk of these are from IAR and ImageCraft.  Some of the files (esp. for Atmel and STMicro) may have some overlap due to processor naming conventions.  Please yell if you have any questions, or if you'd like this refactored.

**Comment by evm-sec** [comment]
Hi just checking to see if you had any thoughts about this PR - I'm happy to refactor it or do something different if you'd like, just let me know.

**Comment by posborne** [comment]
@evm-sec Apologies for the very long delay on this, we are bringing in some new maintainership.  As-is, I don't believe we can move forward with including the changes in tree as they do not consistently follow our policy of ensuring that license is include for each subdirectory or file (which can be challenging to track down).  We may be persuing options for fetchers and the like to get around this while more easily making data available to users when the licensing makes redistribution questionable.

**Comment by evm-sec** [comment]
Hey no worries!  Thanks for getting back to me.  I can check if we have license information and resubmit if so.

**Pull request closed without merging**
